@startuml

cloud "Kredietbank A" {
    [Stratech V1] as KbaStratech
}

cloud "Kredietbank B" {
    [Stratech V2] as KbfStratech
}


cloud "Kredietbank C" {
    [Allegro V1] as KbbAllegro
}

cloud "Kredietbank D" {
    [Allegro V2] as KbcAllegro
}

cloud "Sociale Banken Nederland" {
    package "Waarborgfonds" {
        [Waarborgfonds] as Wsk
        () "API" as API
    }

    [Schuldenknooppunt]    
    [Adapter] as SchuldenknooppuntAdapter

    Wsk <-- API
    API <-- SchuldenknooppuntAdapter
    SchuldenknooppuntAdapter --> Schuldenknooppunt
}

Schuldenknooppunt <-- KbaStratech
Schuldenknooppunt <-- KbfStratech
Schuldenknooppunt <-- KbbAllegro
Schuldenknooppunt <-- KbcAllegro

@enduml