@startuml
autonumber

actor Schuldhulpverlener as user
participant "Kredietbank" as kredietbank
participant "Wsk" as wsk

user -> kredietbank : email verzoek

kredietbank -> wsk : email ontvangen

activate wsk

wsk --> wsk : controleer afzender
wsk --> wsk : maak pro-forma aanvraag link
wsk -> user : email pro-forma aanvraag link

deactivate wsk

user -> wsk : open pro-forma aanvraag link


activate wsk

wsk --> wsk : autoriseer
wsk -> user : toon formulier

deactivate wsk

user -> wsk : verstuur formulier

activate wsk

wsk --> wsk : autoriseer
wsk --> wsk : verwerk aanvraag
wsk -> user : email aanvullende vragen

deactivate wsk

user -> wsk : beantwoord aanvullende vragen

activate wsk

wsk --> wsk : accepteer pro-forma aanvraag
wsk -> user : email geacepteerde pro-forma aanvraag

deactivate wsk

@enduml
