openapi: 3.0.3
info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: ""
paths:
  "/api/kredietbanken/{kredietbank_id}/gebeurtenissen":
    parameters:
      - in: path
        name: kredietbank_id
        required: true
        type: string
        format: uuid
        title: kredietbank id
        description: Uniek identificerend kenmerk van een kredietbank.
        example: 88b33783-0a04-4d94-afae-a6d117d63ad8
      - in: query
        name: offset
        description: An id reference to indicate until where items must be skipped.
        schema:
          type: string
          example: fff29f18-b3f0-490c-a9b9-b795c8eb856b
      - in: query
        name: limit
        description: Value indicating the maximum number requested responses.
        schema:
          type: integer
          default: 10
          example: 10
          minimum: 1
          maximum: 100
          description: Limit the number of responses.
    get:
      tags:
        - gebeurtenissen
      summary: Geeft een lijst met gebeurtenissen.
      operationId: GeefGebeurtenissen
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                title: gebeurtenissen
                type: object
                required:
                  - links
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      required:
                        - type
                        - message
                      properties:
                        type:
                          type: string
                          description: The type of message.
                          enum:
                            - ERROR
                            - WARN
                            - INFO
                          example: ERROR
                        message:
                          type: string
                          description: The message.
                          example: Service x could not be reached.
                  links:
                    type: object
                    required:
                      - next
                    properties:
                      next:
                        type: string
                        format: uri
                        description: Link to the next offset.
                        example: https://service.domain.com/api/action?offset=f64910e7-1006-4c0c-b1fa-10033855770f&limit=100
                  gebeurtenissen:
                    type: array
                    items:
                      type: object
                      required:
                        - event_id
                        - kenmerk
                        - links
                        - naam
                        - occurred
                      title: gebeurtenis
                      properties:
                        event_id:
                          type: string
                          format: uuid
                          description: Unique of the event. May be used as an idemptotency key.
                          example: afa0f657-ba5b-4f6f-bc4e-6ac8dd63d76b
                        occurred:
                          type: string
                          format: date-time
                          description: Time when the event has occurred.
                        correlation_id:
                          type: string
                          format: uuid
                          description: Id of the first command which has started a chain of commands. May
                            be empty if it's the beginning of a command chain.
                          example: 48c274d1-0976-49ca-bb70-6e3ced85b629
                        causation_id:
                          type: string
                          format: uuid
                          description: Id of the command which has caused this event to be triggered.
                          example: e62c8928-026e-493b-9ad1-1ffca6e19e61
                        naam:
                          type: string
                          title: naam
                          description: Naam van de gebeurtenis.
                          example: Aanvraag geaccepteerd
                        kenmerk:
                          type: string
                          title: kenmerk
                          description: >
                            Uniek identificerend kenmerk vastgesteld en
                            geregistreerd door de aanvager. Dit kenmerk moet
                            uniek zijn voor de aanvager.
                          example: 5461135-1
                        links:
                          type: object
                          properties:
                            details:
                              type: string
                              format: uri
                              description: De link naar de api resource (aggregate root) van deze
                                gebeurtenins.
                              example: https://waarborgfonds.sbn.nl/api/borgstellingen/f242f4e7-4ddc-4dbb-a3c1-9ab1a1dea74e
                            document:
                              type: string
                              format: uri
                              description: Link naar het document.
                              readOnly: true
                              example: https://waarborgfonds.sbn.nl/kredietbanken/88b33783-0a04-4d94-afae-a6d117d63ad8/documenten/f242f4e7-4ddc-4dbb-a3c1-9ab1a1dea74e.pdf
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
