openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/kredietbanken/{kredietbank_id}/beoordeel-aanvraag-taken/{taak_id}:    
    parameters:
      - $ref: "../../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - beoordeel aanvraag taken
      summary: Geeft een beoordeel aanvraag taak.
      operationId: GeefBeoordeelAanvraagTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../../../data-dictionary/responses/beoordeel_aanvraag_uitgebreid_taak.yml"
        400:
          $ref: "../../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../../data-dictionary/responses/types/404.yml"

  /api/kredietbanken/{kredietbank_id}/beoordeel-aanvraag-taken/{taak_id}/goedkeuren:
    parameters:
      - $ref: "../../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Voltooit de beoordeel aanvraag taak met goedkeuren.
      operationId: VoltooiBeoordeelAanvraagTaakMetGoedkeurenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../../../data-dictionary/commands/keur_aanvraag_goed.yml"
      responses:
        202:
          $ref: "../../../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../../data-dictionary/responses/types/404.yml"

  /api/kredietbanken/{kredietbank_id}/beoordeel-aanvraag-taken/{taak_id}/afwijzen:
    parameters: 
      - $ref: "../../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Voltooit de beoordeel aanvraag taak met afwijzen.
      operationId: VoltooiBeoordeelAanvraagTaakMetAfwijzenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../../../data-dictionary/commands/wijs_aanvraag_af.yml"
      responses:
        202:
          $ref: "../../../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../../data-dictionary/responses/types/404.yml"

  /api/kredietbanken/{kredietbank_id}/beoordeel-aanvraag-taken/{taak_id}/vraag-stellen:
    parameters:
      - $ref: "../../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Voltooit de beoordeel aanvraag taak met vraag stellen.
      operationId: VoltooiBeoordeelAanvraagTaakMetVraagStellenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../../../data-dictionary/commands/stel_aanvullende_vragen.yml"
      responses:
        202:
          $ref: "../../../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../../data-dictionary/responses/types/404.yml"

  /api/kredietbanken/{kredietbank_id}/beoordeel-aanvraag-taken/{taak_id}/advies-vragen:
    parameters:
      - $ref: "../../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Voltooit de beoordeel aanvraag taak met advies vragen.
      operationId: VoltooiBeoordeelAanvraagTaakMetAdviesVragenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../../../data-dictionary/commands/vraag_advies.yml"
      responses:
        202:
          $ref: "../../../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../../data-dictionary/responses/types/404.yml"