openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:
  
  /api/kredietbanken/{kredietbank_id}/borgstellingen:
    parameters:
      - $ref: "../../../data-dictionary/parameters/kredietbank_id.yml"
    patch:
      tags:
        - borgstelling aanvullen
      summary: Actieve borgstellingen aanvullen met informatie.
      operationId: VulBorgstellingenAanV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../../../data-dictionary/commands/verwerk_saneringskredieten_informatie.yml"
              discriminator:
                propertyName: actie
                mapping:
                  verwerk_saneringskredieten_informatie: "../../../data-dictionary/commands/verwerk_saneringskredieten_informatie.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
