@startuml
autonumber

actor Kredietbank as user
participant "Schuldenknooppunt" as skp
participant "Waarborgfonds" as wsk

user -> skp : bestand

activate skp

skp --> skp : conversie naar saneringskredieten

skp -> wsk : bericht

activate wsk

skp -> user : bestand verstuurd

deactivate skp


wsk -> wsk : borgstellingen ophalen

loop borgstellingen
    wsk --> wsk : bereken verschil met saneringskredieten
end

loop saneringskredieren
    wsk --> wsk : bereken verschil met borgstellingen
end

loop opdrachten
    wsk -> wsk : verwerk opdrachten
end

deactivate wsk

@enduml
