@startuml
autonumber

actor Kredietbank as user
participant "Browser" as browser
participant "Schuldenknooppunt" as api

user -> browser : bestand

activate browser

browser --> browser : conversie naar saneringskredieten

loop borgstellingen
    browser -> api : GET borgstellingen
    api -> browser : borgstellingen
end


loop borgstellingen
    browser --> browser : bereken delta met saneringskredieten
end

loop saneringskredieren
    browser --> browser : bereken delta met borgstellingen
end

browser -> user : opdrachten

deactivate browser

user -> browser : verstuur oprdrachten

activate browser

loop opdrachten
    browser -> api : POST opdracht
    api -> browser : Geaccepteerd
end

browser -> user : opdrachten verstuurd

deactivate browser

@enduml
