openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:

  /api/geef-aanvullende-uitbetaling-informatie-taken/{taak_id}:
    parameters:
      - $ref: "../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - geef aanvullende uitbetaling informatie taken
      summary: Geeft een geef aanvullende uitbetalinginformatie taak.
      operationId: GeefGeefAanvullendeInformatieTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../../data-dictionary/responses/geef_aanvullende_uitbetaling_informatie_taak.yml"
        400:
          $ref: "../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../data-dictionary/responses/types/404.yml"

  /api/geef-aanvullende-uitbetaling-informatie-taken/{taak_id}/informeren:
    parameters:
      - $ref: "../../../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - geef aanvullende uitbetaling informatie taken
      summary: Voltooit de geef aanvullende uitbetaling informatie taak met informeren.
      operationId: VoltooiGeefAanvullendeUitbetalingInformatieTaakMetInformerenTaakV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../../data-dictionary/commands/geef_aanvullende_uitbetaling_informatie.yml"
      responses:
        202:
          $ref: "../../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../../data-dictionary/responses/types/404.yml"