openapi: 3.0.3
info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: ""
paths:
  "/api/kredietbanken/{kredietbank_id}/borgstellingen":
    parameters:
      - in: path
        name: kredietbank_id
        required: true
        type: string
        format: uuid
        title: kredietbank id
        description: Uniek identificerend kenmerk van een kredietbank.
        example: 88b33783-0a04-4d94-afae-a6d117d63ad8
    patch:
      tags:
        - borgstelling aanvullen
      summary: Actieve borgstellingen aanvullen met informatie.
      operationId: VulBorgstellingenAanV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - actie
                    - command_id
                    - correlation_id
                    - saneringskredieten
                  title: verwerk saneringskredieten informatie
                  properties:
                    command_id:
                      type: string
                      format: uuid
                      description: Unique of the command. May be used as an idemptotency key.
                      example: afa0f657-ba5b-4f6f-bc4e-6ac8dd63d76b
                    correlation_id:
                      type: string
                      format: uuid
                      description: Id of the first command which has started a chain of commands. May
                        be empty if it's the beginning of a command chain.
                      example: 48c274d1-0976-49ca-bb70-6e3ced85b629
                    causation_id:
                      type: string
                      format: uuid
                      description: Id of the (last) command which has caused this command to be
                        triggered.
                      example: e62c8928-026e-493b-9ad1-1ffca6e19e61
                    actie:
                      example: verwerk_saneringskredieten_informatie
                      type: string
                      description: De naam van de actie die uitgevoerd wordt. De waarde wordt gebruikt
                        om verschillende type acties op een resource te
                        identificeren.
                    saneringskredieten:
                      type: array
                      minItems: 1
                      items:
                        required:
                          - betalingen
                          - betalingsregeling
                          - borgstelling_id
                          - dubieus
                          - kenmerk
                          - kredietsom
                          - uitbetaaldatum
                        type: object
                        properties:
                          borgstelling_id:
                            type: string
                            format: uuid
                            title: borgstelling
                            description: Uniek identificerend kenmerk van de borgstelling aanvraag.
                            example: afa0f657-ba5b-4f6f-bc4e-6ac8dd63d76b
                          kenmerk:
                            type: string
                            title: kenmerk
                            description: >
                              Uniek identificerend kenmerk vastgesteld en
                              geregistreerd door de aanvager. Dit kenmerk moet
                              uniek zijn voor de aanvager.
                            example: 5461135-1
                          uitbetaaldatum:
                            type: string
                            format: date
                            title: uitbetaaldatum
                            description: De datum waarop het saneringskrediet is uitbetaald.
                            example: 2022-01-01
                          kredietsom:
                            type: object
                            title: kredietsom
                            required:
                              - bruto
                              - netto
                            properties:
                              bruto:
                                type: number
                                minimum: 0
                                title: bruto kredietsom
                                description: >
                                  Bedrag uitbetaald aan schuldeisers plus een
                                  kredietvergoeding uitgaande van maandaflossing
                                  maal de looptijd bij aanvang krediet.
                                example: 1825.34
                              netto:
                                type: number
                                minimum: 0
                                title: netto kredietsom
                                description: |
                                  Bedrag uitbetaald aan schuldeisers
                                example: 1550.77
                          betalingen:
                            type: object
                            title: betalingen
                            description: Hoeveel heeft de client betaald?
                            required:
                              - laatste_aflosdatum
                              - aflossing
                              - kredietvergoeding
                              - vertragingsrente
                              - boete_rente
                            properties:
                              laatste_aflosdatum:
                                type: string
                                format: date
                                title: laatste aflosdatum
                                description: De datum van de laatste aflossing op het saneringskrediet.
                                example: 2022-01-01
                              aflossing:
                                type: number
                                minimum: 0
                                title: aflossing
                                example: 300.47
                              kredietvergoeding:
                                type: number
                                minimum: 0
                                title: kredietvergoeding
                                description: >
                                  De vergoeding die een kredietbank ontvangt
                                  voor de verstrekking en inning van een
                                  saneringskrediet.
                                example: 24.45
                              vertragingsrente:
                                type: number
                                minimum: 0
                                title: vertragingsrente
                                description: >
                                  De vergoeding die berekend wordt over de
                                  achterstand.
                                example: 4.45
                              boete_rente:
                                type: number
                                minimum: 0
                                title: boete rente
                                description: >
                                  De vergoeding die wordt berekend bij
                                  vervroegde aflossing of de kosten die extra in
                                  rekening worden gebracht.
                                example: 1.12
                          achterstanden:
                            type: object
                            title: achterstanden
                            description: Wat zijn de achterstanden van de client?
                            required:
                              - aflossing
                              - kredietvergoeding
                              - vertragingsrente
                              - boete_rente
                            properties:
                              aflossing:
                                type: number
                                minimum: 0
                                title: aflossing
                                example: 300.47
                              kredietvergoeding:
                                type: number
                                minimum: 0
                                title: kredietvergoeding
                                description: >
                                  De vergoeding die een kredietbank ontvangt
                                  voor de verstrekking en inning van een
                                  saneringskrediet.
                                example: 24.45
                              vertragingsrente:
                                type: number
                                minimum: 0
                                title: vertragingsrente
                                description: >
                                  De vergoeding die berekend wordt over de
                                  achterstand.
                                example: 4.45
                              boete_rente:
                                type: number
                                minimum: 0
                                title: boete rente
                                description: >
                                  De vergoeding die wordt berekend bij
                                  vervroegde aflossing of de kosten die extra in
                                  rekening worden gebracht.
                                example: 1.12
                          voorstand:
                            type: number
                            minimum: 0
                            title: voorstand
                            description: >
                              Er is sprake van een voorstand wanneer het
                              uitstaand saldo kleiner is dan het theoretisch
                              saldo.
                            example: 10.15
                          betalingsregeling:
                            type: boolean
                            title: betalingsregeling
                            description: Is er een betalingsregeling actief voor de achterstand op het
                              saneringskrediet
                            example: true
                          dubieus:
                            type: boolean
                            title: dubieus
                            description: Is het saneringskrediet als dubieus aangemerkt?
                            example: true
              discriminator:
                propertyName: actie
                mapping:
                  verwerk_saneringskredieten_informatie: ../../../data-dictionary/commands/verwerk_saneringskredieten_informatie.yml
      responses:
        "202":
          description: Accepted
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status code.
                    example: 404
                  title:
                    type: string
                    description: A short, human-readable summary of the problem type.
                    example: Resource not found
                  detail:
                    type: string
                    description: A human-readable explanation specific to this occurrence of the
                      problem.
                required:
                  - status
                  - title
