@startuml

cloud "Sociale Banken Nederland" {
    package "Waarborgfonds" {
        [Waarborgfonds] as Wsk
        [Adapter] as SchuldenknooppuntAdapter

        Wsk <-- SchuldenknooppuntAdapter
    }

    package "Schuldenknooppunt" as S  {
        interface HTTP
        [Schuldenknooppunt]
    }

    SchuldenknooppuntAdapter --> HTTP : SOAP, X.509
    HTTP <--> Schuldenknooppunt
}
    
collections Kredietbanken
Kredietbanken -> HTTP

@enduml