@startuml

cloud "Sociale Banken Nederland" {
    package "Waarborgfonds" {
        [Waarborgfonds] as Wsk
        () "API" as API
    }

    [Schuldenknooppunt]    
    [Adapter] as SchuldenknooppuntAdapter

    Wsk <-- API
    API <-- SchuldenknooppuntAdapter
    SchuldenknooppuntAdapter --> Schuldenknooppunt
}

@enduml