openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:
  
  /api/borgstelling-categorieen:
    post:
      tags:
        - borgstelling categorieën
      summary: Maakt een borgstelling categorie
      operationId: MaakBorgstellingCategorieV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../data-dictionary/commands/maak_borgstelling_categorie.yml"
      responses:
        201:
          $ref: "../../data-dictionary/responses/types/201.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
    get:
      tags:
        - borgstelling categorieën
      summary: Geeft een lijst van borgstelling categorieën
      operationId: GeefGorgstellingCategorieenV1
      parameters:
        - $ref: "../../data-dictionary/parameters/limit.yml"
        - $ref: "../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/geef_borgstelling_categorieen.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"

  /api/borgstelling-categorieen/{borgstelling_categorie_id}:
    parameters:
      - $ref: "../../data-dictionary/parameters/borgstelling_categorie_id.yml"
    get:
      tags:
        - borgstelling categorieën
      summary: Geeft een borgstelling categorie
      operationId: GeefBorgstellingCategorieV1
      responses:
        200:          
          description: OKmaak
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/geef_borgstelling_categorie.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"
    put:
      tags:
        - borgstelling categorieën
      summary: Wijzigt een borgstelling categorie
      operationId: WijzigBorgstellingCategorieV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../data-dictionary/commands/wijzig_borgstelling_categorie.yml"
      responses:
        202:
          $ref: "../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"
    delete:
      tags:
        - borgstelling categorieën
      summary: Zet een borgstelling categorie uit
      operationId: ZetborgstellingCategorieUitV1
      responses:
        202:
          $ref: "../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"