@startuml


interface Uitvoeringsorgansatie
class SBN

interface Verstrekker
class SBF

interface Contractant
class Kredietbank

interface Handelsmerk
class Wsk

SBF ..|> Verstrekker : "is de verstrekker"
Verstrekker --> Contractant : "Verstrekt borgstelling aan"
Verstrekker --> Handelsmerk : "Communiceert vanuit"
Verstrekker --> Uitvoeringsorgansatie : "Heeft uitvoering uitbesteed aan"

Contractant <|.. Kredietbank : "is een contractant"
Handelsmerk <|.. Wsk : "is het handelsmerk"
Uitvoeringsorgansatie <|.. SBN : "is de uitvoeringsorganisatie"

@enduml