@startuml


interface Uitvoeringsorgansatie
class SBN

interface Uitvoerder
class SBF

interface Kredietverstrekker
class Kredietbank

interface Handelsmerk
class Wsk

interface Gemeente

SBF ..|> Uitvoerder : "is de"
Uitvoerder --> Kredietverstrekker : "Verstrekt borgstellingen aan"
Uitvoerder --> Handelsmerk : "Communiceert vanuit"
Uitvoerder --> Uitvoeringsorgansatie : "Heeft uitvoering uitbesteed aan"

Kredietverstrekker <|.. Kredietbank : "is een"
Handelsmerk <|.. Wsk : "is het"
Uitvoeringsorgansatie <|.. SBN : "is de"

Kredietbank "1" *-- "N" Gemeente : "in opdracht van"

@enduml
