@startuml

:Gebruiker:

(geef mijn taken) as (UseCase) << takenlijst >>

(geef mijn taken) as (Plugin1) << plugin >>
(geef mijn taken) as (Plugin2) << plugin >>
(geef mijn taken) as (Plugin3) << plugin >>

Gebruiker --> (UseCase)

(UseCase) --> (Plugin1)
(UseCase) --> (Plugin2)
(UseCase) --> (Plugin3)

@enduml