@startuml
autonumber

actor Gebruiker as user
participant "Mijn taken pagina" as taken
participant "Taak api" as api
participant "Taak pagina" as taak

user -> taken : geef mijn taken
activate taken
loop taak plugins
    taken -> api : geef mijn taken
    api -> taken : taken
end
taken --> taken : taken samenvoegen
taken -> user : taken
deactivate taken

user -> taken : geef taak
activate taken
taken -> api : claim taak
api -> taken: taak geclaimed
taken --> taken : stuur door
deactivate taken

taken -> taak : geef taak
activate taak
taak -> user : taak
deactivate taak

user -> api : taak afronden
api -> user : taak afgerond

@enduml
